---
- job:
    name: mqtt-matrix-bridge-test
    parent: base
    run: playbooks/test.yaml

- job:
    name: mqtt-matrix-bridge-test2
    parent: base
    run: playbooks/test2.yaml

- project:
    name: matofederorg/k8s-cluster-api-provider
    default-branch: main
    merge-mode: "squash-merge"
    periodic-daily:
      jobs:
      - mqtt-matrix-bridge-test
    e2e-quick-test:
      jobs:
        - mqtt-matrix-bridge-test
        - mqtt-matrix-bridge-test2