---
- name: Badge
  hosts: all
  tasks:
  - name: Ensure directory
    file:
      path: "{{ zuul.executor.work_root }}"
      state: directory
  - copy:
      dest: "{{ zuul.executor.work_root }}/artifacts/badge.json"
      content: "{{ badge | to_json }}"
    vars:
      badge:
        schemaVersion: 1
        label: conformance
        message: "{{ 'passing' if zuul_success else 'failed' }}"
        color: "{{ 'green' if zuul_success else 'red' }}"
  - zuul_return:
      data:
        zuul:
          artifacts:
            - name: status
              url: "badge.json"
              metadata:
                 type: badge