---
- name: Cleanup
  hosts: all
  vars:
    cloud_provider: "{{ cloud }}"  # inherited from the parent job
    project_dir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
    project_tf_dir: "{{ project_dir }}/terraform"
    prefix: "{{ ('pr'+ zuul.change + '-' + zuul.build) | truncate(12, True, '') }}"
    testcluster_name: "{{ ('pr'+ zuul.change + '-' + zuul.build) | truncate(12, True, '') }}"
  environment:
    ENVIRONMENT: "{{ cloud_provider }}"
    PATH: "{{ ansible_user_dir }}/.local/bin:{{ ansible_env.PATH }}"
  tasks:
  - name: Ensure environment file
    template:
      src: "templates/environment.tfvars.j2"
      dest: "{{ project_tf_dir }}/environments/environment-{{ cloud_provider }}.tfvars"
  - name: Cleanup - forceclean
    command: "make forceclean"
    args:
      chdir: "{{ project_tf_dir }}"
